# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cce07b97551f56a68d701bbf1edfccfda280856420b8df5392c8ca09dd02e505728ecc49179d5e8d719887c864a6950ad56665ae5bb0f7804c879ef9bd797b82

test:
  secret_key_base: 8d2c3b408edaa452168476c3bc2c0ea8144caf4c1866c12881fe070d1497adf355ec3bc4f3a91f4162800fdb147e22f9627cd8c85a7b7b3a91e3445744e5c3d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
